### ISSUE TITLE
Optimize bestMatch algorithm

### ISSUE THREAD

**Issue by benoror** [ecaresoft/taxi-driver#20]
Quote @pabloemilio97:

> En vez de hacer sort se podría sacar el valor mayor y sería más eficiente.

https://github.com/ecaresoft/taxi-driver/pull/18#discussion_r239891730

https://github.com/ecaresoft/taxi-driver/blob/0527bddb20518c40422bc8a972a599a8c3490870/lib/match.js#L61-L83

**Comment by pabloemilio97** [comment]
Haría algo como esto, donde se itera una vez sobre cada regla, y para cada regla se itera sobre sus parámetros checando si es mejor match que cada uno de los anteriores. Esto mejora el algoritmo de ser `n * m + nlogn` a ser `n * m` donde n es la cantidad de reglas y m la cantidad de parámetros. 

`
function bestMatch(rules, query, params) {
  let maxCount = 0;
  let bestMatchIndex = 0;

  for(int i = 0; i < rules.size(); i++) {
    let currCount = 0;
    for(int j = 0; j < params.size(); j++) {
      if(_.toLower(rules[i][j]) == _.toLower(query[j])) {
        currCount++;
        bestMatchIndex = i;
      }
      maxCount = currCount > maxCount ? currCount : maxCount;
    }
  }
  return rules[bestMatchIndex];
} 
`

**Comment by benoror** [comment]
@pabloemilio97 suena bien! te propongo esto:

- Armate un branch con tus cambios 🎋 
- Corre las [pruebas unitarias](https://github.com/ecaresoft/taxi-driver#tests) para ver que todo siga jalando 🙈 
  - Si algo tronó hay que revisarlo igual ;)
- Abre un PR con los cambios y lo revisamos 😄

**Comment by pabloemilio97** [comment]
@benoror Will do :)

**Comment by pabloemilio97** [comment]
Ya están funcionando todos los casos de prueba excepto uno que mencionó @racrke en el archivo match.test.js . Creemos que ese caso está mal ya que se escoge como correcta una regla que no comparte la mayor cantidad de atributos en común. Abriré el PR para que le eches un ojo :)
