### ISSUE TITLE
Modificar la respuesta de Taxi-Driver 

### ISSUE THREAD

**Issue by Gnikangel** [ecaresoft/taxi-driver#9]
Como propuesta de respuesta del API requerimos los datos de la siguiente manera:

Siendo: 
- Total = subtotal + taxTotal
- TaxTotal = Sum(taxes.amt)
- taxes.amt = subTotal * factor

```json
{
    "error": null,
    "total": 1346.00,
    "taxTotal": 346.00,
    "taxes": [{
            "type": "IVA",
            "rate": 0.16,
            "factor": 0.16,
            "amt": 160
        },
        {
            "type": "ISR",
            "rate": 0.10,
            "factor": 0.116,
            "amt": 116
        },
        {
            "type": "IEPS",
            "rate": 0.05,
            "factor": 0.05,
            "amt": 50
        },
        {
            "type": "LOCAL",
            "rate": 0.02,
            "factor": 0.02,
            "amt": 20
        }
    ]
}
```

**Comment by Gnikangel** [comment]
![captura de pantalla de 2018-11-22 09-54-36](https://user-images.githubusercontent.com/15052060/48913123-18b91a80-ee3d-11e8-9a79-83014947f53c.png)

**Comment by benoror** [comment]
Cómo les comenté en la mañana, moví la lógica de dependencias (a.k.a. secuencias) a las reglas de impuestos, al ser un concern del tex engine, para que no tengan que ser especificadas al hacer la llamada al API:

https://github.com/ecaresoft/taxi-driver/blob/8b6a5f6f5fa65da4b2ed8b6100305a2a4f88d3b7/db.json#L92
